package com.example.compose.ui.theme

import androidx.compose.ui.graphics.Color

class TonalPalette(

    val neutral100: Color=Color.White,
    val neutral99: Color=Color.White,
    val neutral95: Color=Color.White,
    val neutral90: Color=Color.White,
    val neutral80: Color=Color.White,
    val neutral70: Color=Color.White,
    val neutral60: Color=Color.White,
    val neutral50: Color=Color.White,
    val neutral40: Color=Color.White,
    val neutral30: Color=Color.White,
    val neutral20: Color=Color.White,
    val neutral10: Color=Color.White,
    val neutral0: Color=Color.White,

    val neutralVariant100: Color=Color.White,
    val neutralVariant99: Color=Color.White,
    val neutralVariant95: Color=Color.White,
    val neutralVariant90: Color=Color.White,
    val neutralVariant80: Color=Color.White,
    val neutralVariant70: Color=Color.White,
    val neutralVariant60: Color=Color.White,
    val neutralVariant50: Color=Color.White,
    val neutralVariant40: Color=Color.White,
    val neutralVariant30: Color=Color.White,
    val neutralVariant20: Color=Color.White,
    val neutralVariant10: Color=Color.White,
    val neutralVariant0: Color=Color.White,

    val primary100: Color=Color.White,
    val primary99: Color=Color.White,
    val primary95: Color=Color.White,
    val primary90: Color=Color.White,
    val primary80: Color=Color.White,
    val primary70: Color=Color.White,
    val primary60: Color=Color.White,
    val primary50: Color=Color.White,
    val primary40: Color=Color.White,
    val primary30: Color=Color.White,
    val primary20: Color=Color.White,
    val primary10: Color=Color.White,
    val primary0: Color=Color.White,

    val secondary100: Color=Color.White,
    val secondary99: Color=Color.White,
    val secondary95: Color=Color.White,
    val secondary90: Color=Color.White,
    val secondary80: Color=Color.White,
    val secondary70: Color=Color.White,
    val secondary60: Color=Color.White,
    val secondary50: Color=Color.White,
    val secondary40: Color=Color.White,
    val secondary30: Color=Color.White,
    val secondary20: Color=Color.White,
    val secondary10: Color=Color.White,
    val secondary0: Color=Color.White,

    val tertiary100: Color=Color.White,
    val tertiary99: Color=Color.White,
    val tertiary95: Color=Color.White,
    val tertiary90: Color=Color.White,
    val tertiary80: Color=Color.White,
    val tertiary70: Color=Color.White,
    val tertiary60: Color=Color.White,
    val tertiary50: Color=Color.White,
    val tertiary40: Color=Color.White,
    val tertiary30: Color=Color.White,
    val tertiary20: Color=Color.White,
    val tertiary10: Color=Color.White,
    val tertiary0: Color=Color.White,
)